name: Tool-Man Demo

on:
  - push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        git_ref_name=$(echo "${{ github.ref }}" | awk -F '/' '{print $NF}')
        docker build . --file Dockerfile --tag tool-man:demo-${git_ref_name}
        docker tag tool-man:demo-${git_ref_name} tool-man:demo
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy SIT Env
      run: |
        echo 'This is a DEMO for deployment'
  sit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: System Integration Testing
      run: |
        docker run -v output:/workspace/output --rm tool-man:demo -c "./sraf-cmd --config config/demo.yaml --tag demo" || exit 0
    - name: Return Execution Results to Xray
      run: |
        curl -X POST -H "Content-Type: multipart/form-data" -u ${{ secrets.JIRA_USER }}:${{ secrets.JIRA_PASS }} -F "file=@output/output.xml" "${{ secrets.JIRA_URL }}/rest/raven/1.0/import/execution/robot?projectKey=${{ secrets.JIRA_PROJECT }}&testPlanKey=${{ secrets.JIRA_TESTPLAN }}"
